### ISSUE TITLE
Error trying to install ckan using "Option 1: Virtual Machine creation"

### ISSUE THREAD

**Issue by gianmere** [datagovuk/dgu-vagrant-puppet#54]
Hi, I'm trying to install ckan using "Option 1: Virtual Machine creation".
After I launch a fully provisioned Virtual Machine with the command "vagrant up" I have this errors:

notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns: The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns: Collecting nltk==2.0.4
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Extracting in /tmp/tmpkwuZ1q
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Now working in /tmp/tmpkwuZ1q/distribute-0.6.21
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Building a Distribute egg in /tmp/pip-build-KuWMS3/nltk
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     /tmp/pip-build-KuWMS3/nltk/distribute-0.6.21-py2.7.egg
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Traceback (most recent call last):
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:       File "<string>", line 20, in <module>
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:       File "/tmp/pip-build-KuWMS3/nltk/setup.py", line 32, in <module>
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:         del sdist.finders[:]
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     AttributeError: 'module' object has no attribute 'finders'
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Complete output from command python setup.py egg_info:
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Extracting in /tmp/tmpkwuZ1q
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Now working in /tmp/tmpkwuZ1q/distribute-0.6.21
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Building a Distribute egg in /tmp/pip-build-KuWMS3/nltk
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     /tmp/pip-build-KuWMS3/nltk/distribute-0.6.21-py2.7.egg
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Traceback (most recent call last):
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:       File "<string>", line 20, in <module>
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:       File "/tmp/pip-build-KuWMS3/nltk/setup.py", line 32, in <module>
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:         del sdist.finders[:]
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     AttributeError: 'module' object has no attribute 'finders'
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     ----------------------------------------
notice: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns:     Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KuWMS3/nltk
err: /Stage[main]/Dgu_ckan/Dgu_ckan::Pip_package[nltk==2.0.4]/Exec[pip_install_nltk==2.0.4]/returns: change from notrun to 0 failed: /home/co/ckan/bin/pip install --no-index --find-links=file:///vagrant/pypi --log-file /home/co/ckan/pip.log nltk==2.0.4 returned 1 instead of one of [0] at /etc/puppet/modules/dgu_ckan/manifests/pip_package.pp:22

After that, I have a lot of "Dependency Exec[pip_install_nltk==2.0.4] has failures: true" and "Skipping because of failed dependencies".

What is my mistake ?
Thanks

**Comment by gianmere** [comment]
Here there is the solution:

https://github.com/nltk/nltk/issues/824

Bye

**Comment by davidread** [comment]
Just flagging that there is a bit more about this here: https://github.com/datagovuk/dgu-vagrant-puppet/issues/56
